WebApplication/WebApplication/Models/ErrorViewModel.cs
using System;

namespace WebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication/WebApplication/Models/TasksToDo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PerfectChannel.WebApi.Models
{
    public class TasksToDo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public bool Completed { get; set; }
    }
}

WebApplication/WebApplication/Controllers/TasksToDoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PerfectChannel.WebApi.Models;
using WebApplication.Data;

namespace WebApplication.Controllers
{
    [EnableCors("AllowOrigin")]
    public class TasksToDoesController : Controller
    {
        private readonly WebApplicationContext _context;

        public TasksToDoesController(WebApplicationContext context)
        {
            _context = context;
        }

        // GET: TasksToDoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.TasksToDo.ToListAsync());
        }

        // GET: TasksToDoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasksToDo = await _context.TasksToDo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tasksToDo == null)
            {
                return NotFound();
            }

            return View(tasksToDo);
        }

        // GET: TasksToDoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TasksToDoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Desc,Completed")] TasksToDo tasksToDo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tasksToDo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tasksToDo);
        }

        // GET: TasksToDoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasksToDo = await _context.TasksToDo.FindAsync(id);
            if (tasksToDo == null)
            {
                return NotFound();
            }
            return View(tasksToDo);
        }

        // POST: TasksToDoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Desc,Completed")] TasksToDo tasksToDo)
        {
            if (id != tasksToDo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tasksToDo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TasksToDoExists(tasksToDo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tasksToDo);
        }

        // GET: TasksToDoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasksToDo = await _context.TasksToDo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tasksToDo == null)
            {
                return NotFound();
            }

            return View(tasksToDo);
        }

        // POST: TasksToDoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tasksToDo = await _context.TasksToDo.FindAsync(id);
            _context.TasksToDo.Remove(tasksToDo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TasksToDoExists(int id)
        {
            return _context.TasksToDo.Any(e => e.Id == id);
        }
    }
}

WebApplication/WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TasksToDoes" asp-action="Index">Tasks to do</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication - <a asp-area="" asp-controller="TasksToDoes" asp-action="Index">Tasks</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebApplication/WebApplication/Views/TasksToDoes/Create.cshtml
@model PerfectChannel.WebApi.Models.TasksToDo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TasksToDo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Desc" class="control-label"></label>
                <input asp-for="Desc" class="form-control" />
                <span asp-validation-for="Desc" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Completed" /> @Html.DisplayNameFor(model => model.Completed)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication/WebApplication/Views/TasksToDoes/Delete.cshtml
@model PerfectChannel.WebApi.Models.TasksToDo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TasksToDo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Completed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Completed)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication/WebApplication/Views/TasksToDoes/Details.cshtml
@model PerfectChannel.WebApi.Models.TasksToDo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TasksToDo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Completed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Completed)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication/WebApplication/Views/TasksToDoes/Edit.cshtml
@model PerfectChannel.WebApi.Models.TasksToDo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TasksToDo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Desc" class="control-label"></label>
                <input asp-for="Desc" class="form-control" />
                <span asp-validation-for="Desc" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Completed" /> @Html.DisplayNameFor(model => model.Completed)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication/WebApplication/Views/TasksToDoes/Index.cshtml
@model IEnumerable<PerfectChannel.WebApi.Models.TasksToDo>

@{
    ViewData["Title"] = "Index";
}

<h1>My tasks</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div width="50%">
    <table class="table">
        <thead>
            Pending
        </thead>
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Desc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Completed)
                </th>
                <th>Setting</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Where(a => a.Completed == false).ToList())
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Desc)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Completed)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div width="50%">
    <table class="table">
        <thead>
            Completed
        </thead>
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Desc)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Completed)
                </th>
                <th>Setting</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Where(a => a.Completed == true).ToList())
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Desc)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Completed)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>